# site settings
title: MOOLAH
subtitle: 
email: vivkittykat@gmail.com
description: Loan Analysis Support, Problem-Resolution & Applicant Communication.<br />
baseurl: "/moolah-cash" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: P.O. Box 6101
city: North Hollywood
state: CA
zip_code: 91505
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/vivloans
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
